version: 2
jobs:
  build:
    docker:
      - image: alpine

    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: install dependencies
          command: |
            apk add --no-cache docker docker-compose git
            git clone https://github.com/GeoNode/geonode.git -b 2.10.x --depth 1

      - run:
          name: run tests
          command: |
            ./test-docker.sh
